spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/footour
    username: postgres
    password: postgres
server:
  port: 8080